export const MODELS = 
    [{brandName : "Оберіть бренд", Models : [ "Оберіть модель"]},
    {brandName : "TOYOTA", Models : ["Оберіть модель", "Auris","Avensis", "Corolla", "Camry", "CH-R","Land Cruiser Prado", "RAV-4", "Yaris"]},
    {brandName: "BMW", Models : ["Оберіть модель", "3 E36","3 E46","3 E90","3 F30", "5 E39", "5 E60", "5 F10", "7 E38", "7 E65", "7 F01", "X3 E83", "X3 F25", "X3 G01","X4 F26", "X4 G02", "X5 E53", "X5 E70", "X5 F15", "X5 G05"]},
    {brandName: "SUBARU", Models:  ["Оберіть модель", "Outback", "Legacy", "Forester", "Impreza", "SVX"]},
    {brandName : "MAZDA", Models : ["Оберіть модель", "3", "6", "CX-3", "CX-5", "CX-9"]},
    {brandName : "HYUNDAI", Models : ["Оберіть модель", "Accent", "Sonata", "Elantra", "Tucson", "Santa Fe", "i10", "i30", "Gets", "Kona", "IX35"]},
    {brandName : "AUDI", Models : ["Оберіть модель", "A3", "A4", "A6", "A7", "A8", "Q3", "Q5", "Q7"]},
    {brandName : "MB", Models : ["Оберіть модель", "A-Class", "B-Class", "E-Class", "C-Class", "S-Class", "ML", "GL"]},
    {brandName : "JEEP", Models : ["Оберіть модель", "Cherokee", "Compass", "Patriot", "Renegade", "Wrangler"]},
    {brandName : "FIAT", Models : ["Оберіть модель", "Scudo", "Doblo", "Panda", "Punto", "500"]},
    {brandName : "KIA", Models : ["Оберіть модель", "Ceed","Cerato", "Sorento", "Sportage", "Soul","Magentis", "Optima", "RIO"]},
    {brandName : "FORD", Models : ["Оберіть модель", "Edge","Escape","C-MAX","S-MAX", "Fiesta", "Fusion", "Focus", "Galaxy", "Kuga", "Mondeo", "Ranger", "Transit", ]},
    {brandName : "VW", Models : ["Оберіть модель", "Bora","Caddy","Golf IV","Golf V","Golf VI","Golf VII","Jetta", "Multivan", "Passat V", "Passat VI", "Passat VII", "Polo", "Sharan", "Tiguan", "Touareg", "Touran", "Transporter", ]},
    {brandName : "SKODA", Models : ["Оберіть модель", "Fabia","Octavia","Karoq","Rapid","Superb","Roomster"]},
    {brandName : "NISSAN", Models : ["Оберіть модель","Rogue", "Juke","Micra","Leaf","Note","Qashqai","Tiida","X-Trail", "Murano", "Primastar", "Teana"]},
    {brandName : "RENAULT", Models : ["Оберіть модель", "Clio","Dokker","Duster","Espace","Fluence","Grand Scenic","Kangoo", "Laguna", "Logan", "Megane", "Megane Scenic", "Polo", "Sandero", "Scenic", "Trafic", "Zoe"]},
    {brandName : "PEUGEOT", Models : ["Оберіть модель", "206","207","208","3008","301","307","308", "308 SW", "407", "5008", "508", "Expert", "Partner" ]},
    {brandName : "MITSUBISHI", Models : ["Оберіть модель", "ASX","Carisma","Colt","Galant","Lancer","Lancer X","Outlander","Pajero"]},
    {brandName : "OPEL", Models : ["Оберіть модель", "Astra G", "Astra H", "Astra J", "Astra K","Combo","Corsa","Insignia","Kadett","Meriva","Omega В", "Vectra B", "Vectra C", "Vectra C", "Vivaro", "Zafira" ]}]
    
