export const IMAGES = [
  { brandName: "TOYOTA", img: "https://edetal.store/media/toyota-7.svg" },
  { brandName: "BMW", img: "https://edetal.store/media/bmw-8.svg" },
  { brandName: "SUBARU", img: "https://edetal.store/media/90/SUBAR.png" },
  { brandName: "MAZDA", img: "https://edetal.store/media/mazda-2.svg" },
  {
    brandName: "HYUNDAI",
    img: "https://edetal.store/media/hyundai-automobiles-1.svg",
  },
  { brandName: "AUDI", img: "https://edetal.store/media/audi-11.svg" },
  { brandName: "MB", img: "https://edetal.store/media/mercedes-benz-8.svg" },
  { brandName: "JEEP", img: "https://edetal.store/media/jeep-5.svg" },
  { brandName: "FIAT", img: "https://edetal.store/media/fiat-logo-1.svg" },
  { brandName: "KIA", img: "https://edetal.store/media/kia-motors.svg" },
  { brandName: "FORD", img: "https://edetal.store/media/ford-8.svg" },
  {
    brandName: "VW",
    img: "https://edetal.store/media/cdnlogo.com_volkswagen.svg",
  },
  { brandName: "SKODA", img: "https://edetal.store/media/skoda-6.svg" },
  { brandName: "NISSAN", img: "https://edetal.store/media/nissan-6.svg" },
  { brandName: "RENAULT", img: "https://edetal.store/media/renault-2.svg" },
  { brandName: "PEUGEOT", img: "https://edetal.store/media/peugeot-8.svg" },
  { brandName: "MITSUBISHI", img: "https://edetal.store/media/mitsubishi.svg" },
  { brandName: "OPEL", img: "https://edetal.store/media/opel-6.svg" },
];
